# Generated by Django 3.1.4 on 2021-01-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='settings',
            field=models.TextField(blank=True, help_text='user settings use json format', verbose_name='settings'),
        ),
    ]
