# Generated by Django 3.1.4 on 2021-01-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcops', '0002_user_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='avatar',
            field=models.ImageField(default='avatar/default.png', upload_to='avatar/%Y/%m/%d', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=models.FileField(blank=True, help_text='存放位置, 从本地选取', upload_to='avatar/%Y/%m/%d', verbose_name='文件地址'),
        ),
    ]
