# Generated by Django 3.1.4 on 2021-01-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcops', '0003_auto_20210120_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=models.FileField(blank=True, default='avatar/default.png', help_text='存放位置, 从本地选取', upload_to='avatar/%Y/%m/%d', verbose_name='文件地址'),
        ),
    ]
