# Generated by Django 3.1.4 on 2021-01-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcops', '0004_auto_20210120_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='testapply',
            name='location',
            field=models.FileField(blank=True, default='avatar/default.png', help_text='存放位置, 从本地选取', upload_to='avatar/%Y/%m/%d', verbose_name='元数据地址'),
        ),
    ]
