# Generated by Django 3.1.4 on 2021-01-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcops', '0005_testapply_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testapply',
            name='end_time',
        ),
        migrations.AlterField(
            model_name='testapply',
            name='location',
            field=models.FileField(blank=True, default='avatar/2021/01/21/test.txt', help_text='存放位置, 从本地选取', upload_to='avatar/%Y/%m/%d', verbose_name='元数据地址'),
        ),
    ]
