# Generated by Django 3.1.4 on 2021-01-21 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcops', '0006_auto_20210121_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='testapply',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='该对象限定的结束时间', null=True, verbose_name='结束时间'),
        ),
    ]
